<x-app-layout>
    <x-slot name="header"><h1 class="text-xl font-semibold text-gray-800">คำสั่งโรงเรียน (เฉพาะ)</h1></x-slot>
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div><h2 class="text-2xl font-bold text-gray-800">รายการคำสั่งโรงเรียน (เฉพาะ)</h2><p class="text-gray-500 mt-1">จัดการคำสั่งเฉพาะทั้งหมด</p></div>
        <a href="{{ route('special-orders.create') }}" class="inline-flex items-center gap-2 px-4 py-2.5 bg-navy-700 text-white rounded-lg hover:bg-navy-800 font-medium"><i data-lucide="plus" class="w-5 h-5"></i><span>เพิ่มคำสั่ง</span></a>
    </div>
    @if (session('success'))<div class="mb-6 p-4 bg-emerald-50 border border-emerald-200 rounded-lg flex items-center gap-3"><i data-lucide="check-circle" class="w-5 h-5 text-emerald-600"></i><span class="text-emerald-700">{{ session('success') }}</span></div>@endif
    <div class="card mb-6"><div class="card-body"><form action="{{ route('special-orders.index') }}" method="GET" class="flex flex-col sm:flex-row gap-4"><div class="relative flex-1"><i data-lucide="search" class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"></i><input type="text" name="search" value="{{ request('search') }}" placeholder="ค้นหาเลขที่คำสั่ง, เรื่อง..." class="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-lg"></div><select name="status" class="px-4 py-2.5 border border-gray-300 rounded-lg"><option value="">ทุกสถานะ</option><option value="draft" {{ request('status') == 'draft' ? 'selected' : '' }}>ฉบับร่าง</option><option value="active" {{ request('status') == 'active' ? 'selected' : '' }}>บังคับใช้</option><option value="cancelled" {{ request('status') == 'cancelled' ? 'selected' : '' }}>ยกเลิก</option></select><button type="submit" class="px-6 py-2.5 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 font-medium">ค้นหา</button></form></div></div>
    <div class="card overflow-hidden"><div class="overflow-x-auto"><table class="w-full"><thead class="bg-gray-50 border-b border-gray-200"><tr><th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase">เลขที่คำสั่ง</th><th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase">วันที่</th><th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase">เรื่อง</th><th class="px-6 py-4 text-center text-xs font-semibold text-gray-600 uppercase">สถานะ</th><th class="px-6 py-4 text-center text-xs font-semibold text-gray-600 uppercase">จัดการ</th></tr></thead><tbody class="divide-y divide-gray-200">@forelse ($orders as $order)<tr class="hover:bg-gray-50"><td class="px-6 py-4 font-medium text-navy-700">{{ $order->order_number }}</td><td class="px-6 py-4 text-gray-600">{{ $order->order_date?->locale('th')->translatedFormat('j M Y') }}</td><td class="px-6 py-4 text-gray-800">{{ Str::limit($order->subject, 40) }}</td><td class="px-6 py-4 text-center">@php $statusColors = ['draft' => 'bg-gray-100 text-gray-700', 'active' => 'bg-emerald-100 text-emerald-700', 'cancelled' => 'bg-red-100 text-red-700']; $statusLabels = ['draft' => 'ฉบับร่าง', 'active' => 'บังคับใช้', 'cancelled' => 'ยกเลิก']; @endphp<span class="inline-flex px-2.5 py-1 rounded-full text-xs font-medium {{ $statusColors[$order->status] ?? '' }}">{{ $statusLabels[$order->status] ?? $order->status }}</span></td><td class="px-6 py-4"><div class="flex items-center justify-center gap-2"><a href="{{ route('special-orders.show', $order) }}" class="p-2 text-gray-500 hover:text-navy-600 hover:bg-gray-100 rounded-lg"><i data-lucide="eye" class="w-4 h-4"></i></a><a href="{{ route('special-orders.edit', $order) }}" class="p-2 text-gray-500 hover:text-amber-600 hover:bg-gray-100 rounded-lg"><i data-lucide="pencil" class="w-4 h-4"></i></a><form action="{{ route('special-orders.destroy', $order) }}" method="POST" class="inline" onsubmit="return confirm('ต้องการลบ?')">@csrf @method('DELETE')<button class="p-2 text-gray-500 hover:text-red-600 hover:bg-gray-100 rounded-lg"><i data-lucide="trash-2" class="w-4 h-4"></i></button></form></div></td></tr>@empty<tr><td colspan="5" class="px-6 py-16 text-center"><div class="flex flex-col items-center"><div class="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4"><i data-lucide="clipboard-signature" class="w-8 h-8 text-gray-400"></i></div><h4 class="text-gray-700 font-medium">ยังไม่มีข้อมูล</h4></div></td></tr>@endforelse</tbody></table></div>@if ($orders->hasPages())<div class="px-6 py-4 border-t border-gray-200">{{ $orders->links() }}</div>@endif</div>
</x-app-layout>
